language: node_js
before_script:
  - npm install -g gatsby
node_js:
  - "stable"
cache:
  directories:
    - node_modules
script:
  - npm install && npm run deploy
deploy:
  provider: pages
  local_dir: public
  on:
    branch: master
